
services:
  markitdown-api:
    image: ghcr.io/sermas-eu/markitdown-http-api
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # - ./markitdown_http_api:/app/markitdown_http_api
      - ./.env:/app/.env
    ports:
      - 5012:5012
    develop:
      watch:
        - action: sync+restart
          path: ./markitdown_http_api
          target: /app/markitdown_http_api